config/routes.rb
Rails.application.routes.draw do
  root 'application#home'

  # get '/auth/facebook/callback' => 'sessions#create'
  get '/auth/:provider/callback' => 'sessions#create'
  get 'auth/failure', to: redirect('/')

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'

  resources :tags
  resources :comments
  resources :images
  resources :events
  resources :users

# clean up
  resources :users, only: [:show] do
    resources :events, only: [:new, :index, :create, :show]
  end

  resources :events, only: [:show] do
    resources :images
  end

  resources :images, only: [:show] do
    resources :comments
  end

  resources :images, only: [:show] do
    resources :tags
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # has_many :friendships
  # has_many :friends, :through => :friendships
  # has_many :users, :through => :friendships, :foreign_key => "friend_id"
  # ???
  # friended by users (who user was friended by):
  # has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  # has_many :inverse_friends, :through => :inverse_friendships, :source => :user

# below 3 are for inviting other users:
  # has_many :created_events, class_name: "Event"
  # has_many :event_contributors
  # has_many :events, through: :event_contributors

  has_many :events
  has_many :images, through: :events
  has_many :comments

  has_secure_password

  validates_presence_of :email
	validates_uniqueness_of :email

  # works for facebook
  def self.from_omniauth(auth_hash)
    self.where(:email => auth_hash['info']['email']).first_or_create do |user|
      user.password = SecureRandom.hex
    end
  end
end

  # below not used because of invalid SSL Cert issue
  # def self.from_omniauth(auth)
  #   where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
  #     user.provider = auth.provider
  #     user.uid = auth.uid
  #     user.name = auth.info.name
  #     user.email = auth.info.email
  #     user.save!
  #   end
  # end

#   def self.from_omniauth(auth_hash)
#     user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
#     user.name = auth_hash['info']['name']
#     user.email = auth_hash['info']['email']
#     user.password = SecureRandom.hex
#     user.save!
#     user
#   end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.password == @user.password_confirmation
      @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
      flash[:success] = "Welcome to Stillshare!"
    else
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    @events = @user.events
    # @user.created_events
    respond_to do |f|
      f.html { render :show }
      f.json { render json: @user, adapter: :json }
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Your profile was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_user
		@user = User.find_by(id: params[:id])
	end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being created:</h2>

    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <%= f.label :name %>
  <%= f.text_field :name %><br/>
  <%= f.label :email %>
  <%= f.text_field :email %><br/>
  <%= f.label :password %>
  <%= f.password_field :password %><br/>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
<%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= user.name %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<%= @user.name %> Profile
<br></br>

<% if @events.empty? %>
  You don't have any events yet.
<% else %>

Events:
  <br>
  <!-- <% @user.events.each do |event| %>
    <%= link_to event.title, event_path(event) %><br>
  <% end %> -->
<% end %>

<!-- <p>
  <%= link_to "View Events", user_events_path(@user), :class => "view_events" %>
</p> -->

<div class="all_events">
</div>

<div class="event">
</div>

<div class="event_images">
</div>



<br>
<%= link_to "View All Events", events_path %>
<br>
<%= link_to "Create New Event", new_event_path %>
<br>
<%= link_to "Edit Your Profile", edit_user_path(@user) %>
<br>
<%= link_to "View All Users", users_path %>
<br>
<%= link_to "Log Out", signout_path, :method => :delete %>