config/routes.rb
Rails.application.routes.draw do
  root 'application#home'

  # get '/auth/facebook/callback' => 'sessions#create'
  get '/auth/:provider/callback' => 'sessions#create'
  get 'auth/failure', to: redirect('/')

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'

  resources :tags
  resources :comments
  resources :images
  resources :events
  resources :users

# clean up
  resources :users, only: [:show] do
    resources :events, only: [:new, :index, :create, :show]
  end

  resources :events, only: [:show] do
    resources :images
  end

  resources :images, only: [:show] do
    resources :comments
  end

  resources :images, only: [:show] do
    resources :tags
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :images, :dependent => :destroy

  # has_many :event_contributors
  # has_many :contributors, through: :event_contributors, source: "user"

  validates_presence_of :title
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    # if params[:user_id]
    #   @events = Event.find(params[:user_id])
    # else
    #   @events = Event.all
    # end

    @user = User.find(params[:user_id])
    @events = @user.events
    respond_to do |f|
      f.html { render :index }
      f.json { render json: @events, adapter: :json }
    end
  end

  def new
    @event = Event.new(user_id: params[:user_id])
  end

  def create
    @event = current_user.events.create(event_params)
    if @event.save
      redirect_to event_path(@event), notice: "#{@event.title} has been added."
    else
      render :new
    end
  end

  def show

    @event = Event.find_by(id: params[:id])
    # @image = Image.find_by(id: params[:id])
    @images = @event.images
    respond_to do |f|
      f.html { render :show }
      f.json { render json: @event, adapter: :json }
    end
  end

  def edit
    @event = Event.find_by(id: params[:id])
  end

  def update
    @event = Event.find_by(id: params[:id])
    if @event.update(event_params)
      redirect_to event_path(@event), notice: "#{@event.title} has been updated."
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find_by(id: params[:id])
    @event.destroy
    redirect_to user_path(current_user), notice: "#{@event.title} has been deleted."
  end

  private

  def event_params
    params.require(:event).permit(:title, :date, :description, :user_id, :image)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for @event, html: { multipart: true } do |f| %>
<% if @event.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

    <ul>
    <% @event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= f.hidden_field :user_id, :value => params[:user_id].to_i %>

<div class="field">
  <%= f.label :title %>
  <%= f.text_field :title %><br/>
</div>
<div class="field">
  <%= f.label :date %>
  <%= f.text_field :date %><br/>
</div>
<div class="field">
  <%= f.label :description %>
  <%= f.text_field :description %><br/>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>
<%= form_for @event do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br/>
  <%= f.label :date %>
  <%= f.text_field :date %><br/>
  <%= f.label :description %>
  <%= f.text_field :description %><br/>
  <%= f.submit "Update Event" %>
<%end%>

app/views/events/index.html.erb
<!--NOT USED  -->
<% @events.each do |event| %>
  <%= link_to event.title, event_path(event) %>
  <!-- <%= event.date %>
  <%= event.description %> -->
<% end %>

app/views/events/new.html.erb
<h1>Create New Event</h1>
<%= render 'form' %>

app/views/events/show.html.erb
Event Title: <%= @event.title %>
<br></br>
<%= link_to 'Edit Event', edit_event_path(@event) %>
<br>
<%= link_to "Delete Event", @event, method: :delete, data: {confirm: "Are you sure?"}  %>
<br>
<%= link_to "Add Image/s to Event", new_event_image_path(@event) %>
<br>
<%= link_to "Your Profile", user_path(current_user) %>
<br></br>

Images: <br>
<% @images.each do |image| %>
  <%= link_to image.title, event_image_path(image.event, image) if @images %><br>
  <%= link_to image_tag image.image.thumb.url %>
<% end %>

<br></br>
Most Commented Image:<br>
<%= Image.most_commented.title %>

<br></br>
Image Tags:<br>
<% @images.each do |image| %>
  <% image.tags.each do |tag| %>
    <%= link_to tag.content, tag_path(tag) %>
<% end %>
<% end %>