config/routes.rb
Rails.application.routes.draw do
  root 'application#home'

  # get '/auth/facebook/callback' => 'sessions#create'
  get '/auth/:provider/callback' => 'sessions#create'
  get 'auth/failure', to: redirect('/')

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'

  resources :tags
  resources :comments
  resources :images
  resources :events
  resources :users

# clean up
  resources :users, only: [:show] do
    resources :events, only: [:new, :index, :create, :show]
  end

  resources :events, only: [:show] do
    resources :images
  end

  resources :images, only: [:show] do
    resources :comments
  end

  resources :images, only: [:show] do
    resources :tags
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :event
  has_many :comments, :dependent => :destroy
  has_many :image_tags
  has_many :tags, through: :image_tags

  validates_presence_of :title, :date, :image

  mount_uploader :image, ImageUploader

  def self.most_commented
		Image.all.max_by do |image|
			image.comments.count
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
  end

  def new
    # @event = Event.find_by(params[:id])
    @image = Image.new(event_id: params[:event_id])
  end

# add current_user later
  def create
    # @image = current_user.events.images.create(image_params)
    @event = Event.find_by(params[:event_id])
    @image = Image.new(image_params)
    if @image.save
      redirect_to event_path(@image.event), notice: "#{@image.title} has been added."
    else
      render :new
    end
  end

  def show
    # @event = Event.find_by(id: params[:event_id])
    @image = Image.find_by(id: params[:id])
    @comment = Comment.new(image_id: params[:id])
    @comments = @image.comments
    # byebug
    # @comment = @image.comments.build
    respond_to do |f|
      f.html { render :show }
      f.json { render json: @image, adapter: :json }
    end
  end

  def edit
    @image = Image.find_by(id: params[:id])
  end

  def update
    @image = Image.find_by(id: params[:id])
    if @image.update(image_params)
      redirect_to event_image_path(@image), notice: "#{@image.title} has been updated."
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find_by(id: params[:id])
    @image = Image.find_by(id: params[:id])
		@image.destroy
		redirect_to event_path(@image.event), notice: "#{@image.title} has been deleted."
  end

  private

  def image_params
    params.require(:image).permit(:title, :date, :description, :image, :event_id)
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for @image, html: { multipart: true } do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :event_id, :value => params[:event_id].to_i %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Edit Image Title/Date/Description</h1>
<%= render 'form' %>

app/views/images/new.html.erb
<h1>Upload New Image</h1>
<%= render 'form' %>

app/views/images/show.html.erb
Image Title: <%= @image.title %>
<br></br>
<%= link_to image_tag @image.image.thumb.url %>
<br>
Image Date: <%= @image.date %>
<br>
<% if @image.description %>
Image Description:
 <%= @image.description %>
<% end %>


<br>
<%= link_to "Edit Image", edit_image_path(@image) %>
<br>
<%= link_to "Delete Image", @image, method: :delete, data: {confirm: "Are you sure?"}  %>
<br></br>

Image Comments:
<br>
<div class="comments">

<% @image.comments.each do |comment| %>
<!-- <ul> -->
 <%= comment.user.name %> says:
 <% if current_user.id == comment.user.id %>
  <%= link_to comment.content, image_comment_path(comment.image, comment) %>
  <% else %>
  <%= comment.content %>
  <% end %>
    <!-- </ul> -->
<% end %>

</div>
<br>
<!-- <%= link_to "Add Comment", new_image_comment_path(@image, @image.comments.build) %> -->

<%= form_for ([@image, @comment]) do |f| %>
<%= f.label "Comment" %>
<%= f.text_field :content %>
<%= f.hidden_field :image_id, :value => params[:id].to_i %>
<%= f.hidden_field :user_id, :value => params[:user_id].to_i %>
<%= f.submit %>
<% end %>

<br>
Image Tags: <% @image.tags.each do |tag| %>
  <%= link_to tag.content, "/images/#{@image.id}/tags/#{tag.id}" %>
<% end %>
<!-- tag_path(tag) -->
<br>
<%= link_to "Add Tag", new_image_tag_path(@image, @image.tags.build) %>